export default [
  'Tom Österlund',
  'Max Mustermann',
  'John Doe',
  'Erika Musterfrau',
  'Albert Einstein',
  'Barney Stinson',
  'Lily Aldrin',
  'Marshall Eriksen',
  'Ted Mosby',
  'Robin Scherbatsky',
  'Rachel Greene',
  'Monica Geller',
  'Ross Geller',
  'Joey Tribiani',
  'Chandler Bing',
  'Pheobe Buffay',
  'Martin Gruber',
  'Elisabeth Gruber',
  'Janina Elisabeth Parker Larson',
  'Alejandro Montes Oca de Munós',
]
