name: Lint
on:
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4
      - name: Set up Node.js 🟩
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 🛠️
        run: npm i
      - name: Lint TS 🧹
        run: npm run lint:all
      - name: Lint SCSS
        run: npm run lint:scss
